In [1]:
from sqlalchemy import create_engine
import pandas as pd
import pymysql

# added change to import block

In [2]:
USER = 'kctey'
PASSWORD = 'CQu1FxSp'
HOST = '127.0.0.1'
PORT = 3306
DATABASE = 'Library'

engine = create_engine('mysql+pymysql://{0}:{1}@{2}:{3}/{4}'.format(
        USER, PASSWORD, HOST, PORT, DATABASE
))
cursor = engine.connect()

# added change in block 2

In [3]:
sql_statement = """SELECT Authors, MyUnknownColumn as Author1, `MyUnknownColumn_[0]` as Author2, `ï»¿Accession Number`
              FROM LibBooks"""

table_df = pd.read_sql(
    sql_statement,
    con=engine
)
table_df

                         Authors           Author1   Author2 ï»¿Accession Number
0                  George Orwell                                           A01
1         Gabriel Garcia Marquez                                           A02
2                  Aldous Huxley                                           A03
3              Fyodor Dostoevsky                                           A04
4                     C.S. Lewis                                           A05
5                   Mary Shelley                                           A06
6                 John Steinbeck                                           A07
7                     Mark Twain                                           A08
8                Charles Dickens                                           A09
9                  Joseph Heller                                           A10
10                         Homer                                           A11
11                   Victor Hugo                                           A12
12                   James Joyce                                           A13
13              Vladimir Nabokov                                           A14
14                      Ayn Rand                                           A15
15               Patrick Suskind                                           A16
16                   Franz Kafka                                           A17
17             Bret Easton Ellis                                           A18
18                 Rene Goscinny     Albert Uderzo                         A19
19                  Ray Bradbury                                           A20
20                  Isaac Asimov                                           A21
21                     Karl Marx  Friedrich Engels                         A22
22                  Thomas Paine                                           A23
23           Niccolo Machiavelli                                           A24
24                    Adam Smith                                           A25
25  Miguel de Cervantes Saavedra                                           A26
26            Simone de Beauvoir                                           A27
27                 Immanuel Kant                                           A28
28                Charles Darwin                                           A29
29                  Isaac Newton                                           A30
30                 Milan Kundera                                           A31
31                       Sun Tzu                                           A32
32             Jorge Luis Borges                                           A33
33        Gabriel Garcia Marquez                                           A34
34                    Juan Rulfo                                           A35
35                   Octavio Paz                                           A36
36                  Pablo Neruda                                           A37
37               Richard Feynman                                           A38
38               Stephen Hawking                                           A39
39                    Carl Sagan                                           A40
40          Silvanus P. Thompson    Martin Gardner                         A41
41                  Enrico Fermi                                           A42
42            Alexander Hamilton     James Madison  John Jay               A43
43                     John Lcke  C. B. Macpherson                         A44
44                   Karl Popper                                           A45
45                   Howard Zinn                                           A46
46               William Golding                                           A47
47                 George Orwell                                           A48
48              Ernest Hemingway                                           A49
49                 Luo Guanzhong                                           A50

In [17]:
# author insertion
import numpy as np

authors = table_df['Authors']
author1 = table_df['Author1']
author2 = table_df['Author2']
all_authors = np.concatenate((authors, author1, author2))
distinct_authors = np.unique(all_authors)

for author_name in distinct_authors:
    if author_name == '':
        continue
        
    query = "INSERT INTO authors (name) VALUES (%s)"
    cursor.execute(query, (author_name,))

In [19]:
# book_author many-to-many table creation
for idx, row in table_df.iterrows():
    accession_no = row['ï»¿Accession Number']
    author = row['Authors']
        
    query = "INSERT INTO book_author (author_name, book_accession) VALUES (%s, %s)"
    cursor.execute(query, (author, accession_no))
    
    if row['Author1'] != '':
        author1 = row['Author1']
        cursor.execute(query, (author1, accession_no))
    
    if row['Author2'] != '':
        author2 = row['Author2']
        cursor.execute(query, (author2, accession_no))